name: rentarra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  animated_text_kit: ^4.2.2

  # Firebase core
  firebase_core: ^3.13.0

  # Firebase auth
  firebase_auth: ^5.5.2

  # Firestore
  cloud_firestore: ^5.6.6

  # Firebase Storage
  firebase_storage: ^12.4.5

  # Location and map services
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  image_picker: ^1.0.4

  # Shared preferences, state, etc. (if used)
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this later when you have image assets
  # assets:
  #   - assets/images/
