name: rentarra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.8.13
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  firebase_storage_web: ^3.6.22
  js: ^0.7.2
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  animated_text_kit: ^4.2.2
  geocoding: ^2.1.0
  



  # Image picker for uploading property images
  image_picker: ^1.0.4

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this later when you have image assets
  # assets:
  #   - assets/images/
