// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDJMu04a-ItnaEFCbwIjbVfy0pyzkzAI',
    appId: '1:619834203559:web:be57433626573d8d2e2a82',
    messagingSenderId: '619834203559',
    projectId: 'rentarra-83520',
    authDomain: 'rentarra-83520.firebaseapp.com',
    storageBucket: 'rentarra-83520.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4aHioRUBK9fKM-SJK-9wdSuYP2WowVQ',
    appId: '1:619834203559:android:275efd652c74ee652e2a82',
    messagingSenderId: '619834203559',
    projectId: 'rentarra-83520',
    storageBucket: 'rentarra-83520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDjjdHwk6VPeuJ2IWHSOyasJ0DIqMRXng',
    appId: '1:619834203559:ios:ec1683ffff4776e72e2a82',
    messagingSenderId: '619834203559',
    projectId: 'rentarra-83520',
    storageBucket: 'rentarra-83520.firebasestorage.app',
    iosBundleId: 'com.example.rentarra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDjjdHwk6VPeuJ2IWHSOyasJ0DIqMRXng',
    appId: '1:619834203559:ios:ec1683ffff4776e72e2a82',
    messagingSenderId: '619834203559',
    projectId: 'rentarra-83520',
    storageBucket: 'rentarra-83520.firebasestorage.app',
    iosBundleId: 'com.example.rentarra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaDJMu04a-ItnaEFCbwIjbVfy0pyzkzAI',
    appId: '1:619834203559:web:534257a85fa0e68c2e2a82',
    messagingSenderId: '619834203559',
    projectId: 'rentarra-83520',
    authDomain: 'rentarra-83520.firebaseapp.com',
    storageBucket: 'rentarra-83520.firebasestorage.app',
  );
}
